name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'flowcon'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - uses: actions/cache@v2
      name: Set up caches
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdoc3
        pip install .

    - name: Build documentation
      run: |
        pdoc3 flowcon -o docs/ --html --force 

    # Upload for introspection, useful for pull requests and debugging
    - uses: actions/upload-artifact@v3
      with:
        name: generated-site
        path: docs/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/flowcon
