name: Build, lint, and run tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [Dockerfile-pytorch1.13.1, Dockerfile-pytorch2.1.2, Dockerfile-pytorch2.2.2, Dockerfile-pytorchlatest]
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -f ./docker/${{ matrix.dockerfile }} -t flowc-${{ matrix.dockerfile }} .

    - name: Lint with flake8
      run: |
        docker run myapp-${{ matrix.dockerfile }} flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        docker run myapp-${{ matrix.dockerfile }} flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: docker run myapp-${{ matrix.dockerfile }} pytest --cov --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella